### ISSUE TITLE
路徑太深的檔案會clone不到

### ISSUE THREAD

**Issue by 40123156** [chiamingyen/kmol2016#1]
如果clone到桌面或某資料夾
會因為有些檔案的路徑太深而clone不到
解決辦法是clone到根目錄下(如 c:\ 或 d:\ )
即可全部檔案clone到

**Comment by chiamingyen** [comment]
看完這一段, 然後做個結論 pull request 到 cdw2 倉儲

http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows

Yen

40123156 <notifications@github.com> 於 2016年3月11日 上午10:54 寫道：

**Comment by chiamingyen** [comment]
這個可攜的 Windows based 有幾個限制, 前面提到的路徑太長是潛在問題之一, 利用 Zip download 或 Release 的版本下載, 也會產生問題.
目前用戶只能儘量在 C:\ 或 Y:\tmp 短路徑中下載.
